unused_list = [ 
            "ABLED", "ABODE", "ABORT", "ABUSE", "ADORN",
            "AFIRE", "AFOOT", "AFOUL", "AFOUL", "AIDER", "ALGAE", "ALIBI", "ALIGN",
			"ALLAY", "ALLEY", "ALLOT", "ALLOY", "AMAZE", "AMEND", "AMPLY",  
            "ANIME", "ANKLE", "ANNUL", "APING", "APNEA", "ARENA",
            "ARMOR", "AROSE", "ARRAY", "ARSON", "ATTIC", 
            "AUGUR", "AUNTY", "AVIAN", "AVOID", "AXIAL", "AXION", "BAGGY", 
            "BARON", "BASAL", "BASIL", "BASIS", 
            "BEECH", "BEFIT", "BEGAN", "BEGAT", "BEGUN", "BELLE", "BERRY", "BETEL", "BEVEL", "BEZEL", 
            "BIBLE", "BIDDY", "BIGOT", "BILLY", "BINGO", "BISON", "BITTY", 
            "BLAST", "BLEAT", "BLESS", "BLIND", "BLITZ", "BLOAT", 
            "BLOOD", "BLOOM", "BLUER", "BOBBY", "BONEY", 
            "BOOTH", "BOSOM", "BOTCH", "BOULE", "BOUND", "BOWEL", 
		    "BRAWL", "BRICK", "BRINY", "BROIL", "BROOD", "BUDGE",
		    "BURNT", "BURST", "BUSED", "BUSHY", "BUTCH", "BUTTE", "BUXOM", "BUYER", "BYLAW", "CABAL", 
            "CABBY", "CABIN", "CADDY", "CAGEY", "CAIRN", "CANAL", "CAPUT", "CASTE", 
            "CAVIL", "CELLO", "CHAFF", "CHASM", "CHESS", 
            "CHICK", "CHIDE", "CHILI", "CHINA", "CHOMP", "CHUCK", "CHUMP", "CHURN",
		    "CLACK", "CLAIM", "CLANG", "CLANK", "CLASP", "CLEAT", "CLIFF", 
            "CLINK", "CLOUT", "CLUED", "CLUMP", "COBRA", "COLOR", 
            "COMIC", "COPSE", "COUCH", "COUGH", "COUPE", "COVEY", "CRACK", 
            "CRASH", "CREED", "CREEK", "CREEP", "CREME", "CRESS", 
            "CRICK", "CRIED", "CRIER", "CROCK", "CRONY", "CROUP", "CRUDE", "CRUEL", 
            "CRUMP", "CUBIC", "CURRY", "CURVY", "CUTIE", "CYCLE", 
            "DAILY", "DAIRY", "DEALT", "DEBAR", "DECOR", 
            "DEIGN", "DEMON", "DEMUR", "DENSE", "DERBY", "DILLY", "DIMLY", 
            "DIODE", "DIRGE", "DIRTY", "DITCH", "DIVAN", "DIVER", "DIZZY",
            "DOWDY", "DOWNY", "DRAKE", "DRAMA", "DRANK", "DRAWL", 
            "DRESS", "DRIED", "DRIER", "DRIFT", "DROIT", "DROSS", 
            "DROWN", "DRUID", "DRUNK", "DRYLY", "DULLY", "DUMPY", "DUNCE", "DUSKY", 
            "DUSTY", "DYING", "EATEN", "EATER", "ECLAT", "EDICT", "EERIE",
		    "EIGHT", "EKING", "ELECT", "ELEGY", "ELFIN", "ELIDE", "EMBED",
		    "EMCEE", "ENEMY", "ENTRY", "ENVOY", "ERECT", "ESTER", "ETUDE", 
            "EVICT", "EXPEL", "EYING", "FABLE", "FAIRY", "FANNY", 
            "FATAL", "FATTY", "FAUNA", "FECAL", "FELLA", "FELON", "FEMME", "FEMUR", "FENCE", "FETAL", 
            "FETUS", "FICUS", "FIERY", "FIGHT", "FILER", 
            "FILLY", "FILMY", "FILTH", "FIZZY", "FLACK", "FLAKY", "FLECK", "FLEET", "FLIER", 
            "FLUID", "FLUKE", "FLUSH", 
		    "FRAUD", "FREAK", "FREED", "FREER", "FRIAR", "FRISK",  
            "FRUIT", "FUDGE",
		    "FUROR", "FURRY", "FUSSY", "GABLE", "GAFFE", "GAILY", "GASSY", "GATOR",
		    "GAVEL", "GAYER", "GAYLY", "GAZER", "GEEKY", "GIPSY",
		    "GIRLY", "GIVER", "GLOSS", "GODLY", 
            "GOLLY", "GONAD", "GOURD", "GRAPE",
            "GRAZE", "GRILL", "GROPE", "GROWN", 
            "GRUNT", "GUAVA", "GUILT", "GULCH", "GUMBO", "GUSTO", "GUTSY", 
            "GYPSY", "HAREM", "HARPY", "HARRY", "HASTY", 
            "HAUTE", "HEDGE",  
            "HIPPY", "HITCH", "HOIST", "HONOR", "HORNY", "HOTLY", 
            "HUMUS", "HUSKY", "HUSSY", "HYDRO", "HYMEN", "ICILY", 
		    "IDIOT", "IDYLL", "ILIAC", "IMPLY", "INGOT", 
            "INLET", "INTRO", "ISSUE", "JETTY", "JOIST ", 
            "JUICY", "JUMBO", "JUNTA", "JUNTO", "JUROR", "KAPPA", "KINKY", "KITTY", 
            "KNEED", "LADEN",
            "LANCE", "LATCH", "LEANT", "LEGAL", 
	        "LEPER", "LIEGE", "LIKEN", "LIPID",
	        "LOAMY", "LOATH", "LOBBY", "LOGIN", "LOOSE", "LORRY",
	        "LUMEN", "LUPUS", "LURCH", "LYMPH",
	        "LYRIC", "MACRO", "MAFIA", "MAMMA", "MAMMY", 
	        "MANGE", "MANGY", "MANIC", "MEATY", "MECCA",
	        "MELEE", "MILKY", "MINIM", "MINOR", "MISSY", "MOCHA",
	        "MOGUL", "MOODY", "MORON", "MORPH", "MOTIF", "MOUND",
	        "MOVER", "MOWER", "MUCUS", "MUDDY", "MURKY", "MUSKY",
	        "NACHO", "NEWER", "NEWLY",
	        "NIECE", "NINNY", "NOBLY", "NOOSE", "NOSEY",
	        "NOTCH", "NUTTY", "OAKEN", "OBESE", "OCTAL", 
	        "ODDER", "OLDEN", "OMBRE", "OPIUM", "OPTIC",
	        "ORBIT", "OUTGO", "OVARY", "OVATE",
	        "OVINE", "OVOID", "OWING", "PADDY", "PAGAN", "PALER", "PALSY",
	        "PANSY", "PARKA", "PARSE", "PASTE", "PASTY",
	        "PAYEE", "PAYER", "PECAN", "PENAL", "PENCE", "PENNY", 
            "PESTO", "PIGGY", "PIVOT",
	        "PIZZA", "PLACE", 
	        "PLIED", "PLIER", "PLUME", "PLUSH", "POESY", "POOCH",
	        "POSER", "POSIT", "POSSE", "POUCH", "PRAWN", 
		    "PRIED", "PRIVY", "PROOF", 
		    "PRUDE", "PUBIC", "PUDGY", "PUFFY", "PULSE", "PUNCH",
		    "PUPPY", "PUREE", "PURER", "PURSE", "PUSHY", "PUTTY", "PYGMY", "QUACK",
		    "QUARK", "QUASI", "QUEER", "QUELL", 
		    "QUOTH", "RABBI", "RACER", "RADAR", "RADII", "RAJAH", "RALLY", "RALPH",
		    "RANDY", "RARER", "RASPY", "RAVEN", "RAZOR", "REARM",
            "REBAR", "RECUT", "REEDY", "REFIT", "REHAB", "REIGN", "RENAL", 
            "REPLY", "RESET", "RIFLE", "RIGOR", "RINSE", "RIPEN", "RISER",
		    "RISKY", "RIVER", "ROAST", "ROGER", "ROOST", "ROTOR", "RULER", "RUMOR", "RURAL", 
	        "SADLY", "SAFER",
		    "SALON", "SALVE", "SALVO", "SANER", "SAPPY", "SATIN", "SATYR", "SAUCE",
		    "SAVOY", "SCALP", "SCALY", "SCAMP", "SCARY", "SCENE",
		    "SCION", "SCOOP", "SCREE", "SCREW", "SCUBA",  
            "SEIZE", "SEMEN", "SEPIA", "SERIF", "SETUP", "SEWER", "SHACK", "SHADY", 
            "SHALE", "SHALT", "SHARK", "SHEEN", "SHEEP", "SHEER", 
            "SHEIK", "SHIED", "SHINY", "SHIRT", "SHOAL", "SHOCK", "SHONE", 
            "SHOOK", "SHOOT", "SHREW", 
            "SIEVE", "SIGMA", "SILKY", "SINEW", "SINGE", "SIREN", "SIXTY", 
		    "SKULK", "SKULL", "SLACK", "SLAIN", "SLANT", "SLASH", "SLAVE", "SLEET", 
            "SLEPT", "SLICK", "SLIDE", "SLIME", "SLIMY", "SLING", "SLINK", "SLOOP", "SLUNK", "SLURP", 
            "SLUSH", "SLYLY", "SMACK", "SMELL", "SMOKY", "SMOTE", "SNEER", 
            "SNIFF", "SNIPE", "SNORE", "SNOWY", "SNUCK", "SNUFF", "SOAPY", "SOBER", "SONAR", 
            "SOOTH", "SOOTY", "SPANK", "SPAWN",  
            "SPERM", "SPIED", "SPIKY", "SPILT", "SPINY", "SPOOK", "SPREE", 
            "SPUNK", "SPURN", "SQUIB", "STALK", "STALL", "STANK",
            "STAVE", "STEAK", "STEAL", "STEER", 
            "STOKE", "STOOD", "STOOP", "STRIP", "STRUT", "STUCK", 
            "STUFF", "STUNK",
	        "SUING", "SULLY", "SUMAC", "SURGE", "SWAMI", "SWAMP", "SWARM",
	        "SWASH", "SWEAR", "SWEPT", "SWIFT", "SWOOP"
            "SWORE", "SWORN", "SYNOD", "TAINT",
	        "TAKER", "TAMER", "TANGO", "TAROT", "TATTY", "TEARY", "TEDDY",
	        "TENET", "TENSE", "TEPEE", "TERRA", "TESTY", "THEFT",
	        "THETA", "THONG", "TIGHT", "TIMID",
	        "TODDY", "TOKEN", "TONAL", "TONER", "TONGA", 
	        "TORUS", "TRAMP", "TREAD",
	        "TRIAL", "TRIBE", "TRIED", "TRUCE", "TRUER",
	        "TRUMP", "TRUNK", "TUBAL", "TULLE", "TUMOR", 
	        "TWEET", "TWIXT", "TYING", "UMBRA", "UNCUT", 
	        "UNITY", "UNSET", "UNWED", "URINE", "UTILE", "VALOR", 
	        "VALVE", "VAPOR", "VAUNT", "VEGAN", "VERSE", "VERSO",
	        "VICAR", "VIGIL", "VIPER", "VIRUS", "VISIT", "VISTA",
	        "VOCAL", "VOGUE", "VOMIT", "WAGER", 
	        "WAIVE", "WARTY", "WAVER", "WAXEN", "WEAVE", "WEIGH",
	        "WELCH", "WELSH", "WHARF", 
	        "WIDER", "WIDOW", "WIGHT", "WILLY", "WIMPY", "WINCH", "WISER", "WISPY",
	        "WOMEN", "WOODY", "WOOLY", "WOOZY", "WORTH", "WRACK", "WRECK", 
            "WREST", "WRING", "WRYLY", "ZONAL"
             ]

word = 'ABBOT'


if word in unused_list:
 print(f"{word} is in this list -  {word} is available! Guess {word}. Give {word} a try!")
else:
   print(f"{word} is not in this list, Jerk!! {word} has most likely already been used by Wordle.")



            




