unused_list = [ 
            "ABBOT", "ABHOR", "ABLED", "ABODE", "ABORT", "ABUSE", "ADEPT", "ADMIN", "ADORN",
            "AFIRE", "AFOOT", "AFOUL", "AFOUL", "AIDER", "ALARM", "ALGAE", "ALIBI", "ALIGN",
			"ALLAY", "ALLEY", "ALLOT", "ALLOY", "ALONG", "AMAZE", "AMEND", "AMONG", "AMPLY", 
            "AMUSE", "ANIME", "ANKLE", "ANNEX", "ANNOY", "ANNUL", "APING", "APNEA", "ARENA",
            "ARISE", "ARMOR", "AROSE", "ARRAY", "ARROW", "ARSON", "ARTSY", "ASHEN", "ASSAY", "ATTIC", 
            "AUGUR", "AUNTY", "AVIAN", "AVOID", "AWARE", "AWOKE", "AXIAL", "AXION", "BAGGY", 
            "BALER", "BALMY", "BANJO", "BARON", "BASAL", "BASIL", "BASIS", "BATCH", "BEARD", 
            "BEECH", "BEFIT", "BEGAN", "BEGAT", "BEGUN", "BELLE", "BERRY", "BETEL", "BEVEL", "BEZEL", 
            "BIBLE", "BICEP", "BIDDY", "BIGOT", "BILGE", "BILLY", "BINGO", "BISON", "BITTY", 
            "BLANK", "BLAST", "BLEAT", "BLEND", "BLESS", "BLIND", "BLINK", "BLISS", "BLITZ", "BLOAT", 
            "BLOOD", "BLOOM", "BLUER", "BLUNT", "BOARD", "BOBBY", "BONEY", "BONGO",  
            "BOOTH", "BORNE", "BOSOM", "BOTCH", "BOULE", "BOUND", "BOWEL", "BRAND",
		    "BRAWL", "BRICK", "BRINY", "BROIL", "BROOD", "BRUNT", "BUDGE", "BULGE", "BUNNY",
		    "BURNT", "BURST", "BUSED", "BUSHY", "BUTCH", "BUTTE", "BUXOM", "BUYER", "BYLAW", "CABAL", 
            "CABBY", "CABIN", "CACTI", "CADDY", "CAGEY", "CAIRN", "CANAL", "CAPUT", "CASTE", "CATTY",
            "CAVIL", "CEASE", "CELLO", "CHAFF", "CHAIR", "CHASM", "CHESS", 
            "CHICK", "CHIDE", "CHILI", "CHINA", "CHIRP", "CHUCK", "CHUMP", "CHURN",
		    "CIVIL", "CLACK", "CLAIM", "CLAMP", "CLANG", "CLANK", "CLASH", "CLASP", "CLEAT", "CLIFF", 
            "CLINK", "CLOUT", "CLUED", "CLUMP", "CLUNG", "COBRA", "COLOR", "COMFY", 
            "COMIC", "CONCH", "COPSE", "CORAL", "COUCH", "COUGH", "COUPE", "COVEN", "COVEY", "CRACK", 
            "CRASH", "CREED", "CREEK", "CREEP", "CREME", "CRESS", "CREST", 
            "CRICK", "CRIED", "CRIER", "CROCK", "CRONY", "CROUP", "CRUDE", "CRUEL", 
            "CRUMP", "CUBIC", "CURIO", "CURRY", "CURSE", "CURVE", "CURVY", "CUTIE", "CYCLE", 
            "DAILY", "DAIRY", "DALLY", "DATUM", "DAUNT", "DEALT", "DEBAR", "DECOR", "DEFER", 
            "DEIGN", "DEMON", "DEMUR", "DENSE", "DERBY", "DETOX", "DEUCE", "DILLY", "DIMLY", 
            "DIODE", "DIRGE", "DIRTY", "DITCH", "DIVER", "DIZZY", "DODGY", 
            "DOUGH", "DOWDY", "DOWEL", "DOWNY", "DRAKE", "DRAMA", "DRANK", "DRAPE", "DRAWL", 
            "DREAD", "DRESS", "DRIED", "DRIER", "DRIFT", "DRILL", "DROIT", "DRONE", "DROSS", 
            "DROWN", "DRUID", "DRUNK", "DRYLY", "DULLY", "DUMMY", "DUMPY", "DUNCE", "DUSKY", 
            "DUSTY", "DYING", "EAGER", "EATEN", "EATER", "ECLAT", "EDICT", "EDIFY", "EERIE",
		    "EIGHT", "EKING", "ELATE", "ELECT", "ELEGY", "ELFIN", "ELIDE", "ELITE", "EMBED",
		    "EMCEE", "ENEMY", "ENTRY", "ENVOY", "ERASE", "ERECT", "ESTER", "ETUDE", 
            "EVICT", "EXILE", "EXPEL", "EXTOL", "EYING", "FABLE", "FAIRY", "FANNY", 
            "FATAL", "FATTY", "FAUNA", "FECAL", "FELLA", "FELON", "FEMME", "FEMUR", "FENCE", "FETAL", 
            "FETCH", "FETID", "FETUS", "FICUS", "FIERY", "FIFTH", "FIGHT", "FILER", 
            "FILLY", "FILMY", "FILTH", "FIZZY", "FLACK", "FLAKY", "FLECK", "FLEET", "FLIER", 
            "FLUID", "FLUKE", "FLUSH", "FLUTE", "FOAMY", "FOIST", "FOLIO",
		    "FORUM", "FRAUD", "FREAK", "FREED", "FREER", "FRIAR", "FRILL", "FRISK", "FRITZ", 
            "FRUIT", "FUDGE", "FUGUE", 
		    "FUROR", "FURRY", "FUSSY", "GABLE", "GAFFE", "GAILY", "GASSY", "GAUGE",
		    "GAVEL", "GAYER", "GAYLY", "GAZER", "GEEKY", "GEESE", "GENIE", "GHOST", "GIPSY",
		    "GIRLY", "GIVER", "GLADE", "GLARE", "GLINT", "GLOSS", "GNOME", "GODLY", 
            "GOLLY", "GONAD", "GOOEY", "GOURD", "GRAFT", "GRAPE",
            "GRASS", "GRAVE", "GRAVY", "GRAZE", "GRILL", "GROAN", "GROPE", "GROSS", "GROWN", 
            "GRUFF", "GRUNT", "GUAVA", "GUESS", "GUILT", "GUISE", "GULCH", "GUMBO", "GUSTO", 
            "GYPSY", "HABIT", "HARDY", "HAREM", "HARPY", "HARRY", "HASTE", "HASTY", 
            "HAUNT", "HAUTE", "HAVEN", "HAZEL", "HEDGE",  
            "HIPPY", "HITCH", "HOIST", "HOLLY", "HONOR", "HORNY", "HOTLY", "HOVEL",
            "HUMUS", "HUSKY", "HUSSY", "HYDRO", "HYMEN", "ICILY", "IDEAL", "IDIOM",
		    "IDIOT", "IDLER", "IDYLL", "ILIAC", "IMBUE", "IMPLY", "INBOX", "INCUR", "INGOT", 
            "INLET", "INTRO", "ISSUE", "JETTY", "JOIST ", 
            "JUICY", "JUMBO", "JUMPY", "JUNTA", "JUNTO", "JUROR", "KAPPA", "KINKY", "KITTY", 
            "KNEED", "KNIFE", "KNOWN", "KRILL", "LADEN",
            "LANCE", "LATCH", "LATER", "LATHE", "LAUGH", "LEACH", "LEANT", "LEASE",
            "LEAST", "LEFTY", "LEGAL", 
	        "LEPER", "LEVEL", "LEVER", "LIEGE", "LIKEN", "LIMBO", "LIPID",
	        "LIVID", "LLAMA", "LOAMY", "LOATH", "LOBBY", "LOGIN", "LOOSE", "LORRY",
	        "LOUSY", "LUMEN", "LUMPY", "LUPUS", "LURCH", "LURID", "LYMPH",
	        "LYRIC", "MACHO", "MACRO", "MAFIA", "MAKER", "MAMMA", "MAMMY", 
	        "MANGE", "MANGY", "MANIC", "MEATY", "MECCA",
	        "MELEE", "MIGHT", "MILKY", "MINIM", "MINOR", "MINTY", "MIRTH", "MISER", "MISSY", "MOCHA",
            "MODAL", 
	        "MOGUL", "MOLDY", "MOODY", "MORAL", "MORON", "MORPH", "MOTEL", "MOTIF", "MOUND", "MOUTH",
	        "MOVER", "MOWER", "MUCUS", "MUDDY", "MUNCH", "MURKY", "MUSKY",
	        "MYRRH", "NACHO", "NADIR", "NASAL", "NEWER", "NEWLY",
	        "NIECE", "NINNY", "NOBLY", "NOISY", "NOMAD", "NOOSE", "NOSEY",
	        "NOTCH", "NOVEL", "NURSE", "NUTTY", "NYLON", "OAKEN", "OBESE", "OCTAL", 
	        "ODDER", "ODDLY", "OFFER", "OLDEN", "OMBRE", "OMEGA", "OPINE", "OPIUM", "OPTIC",
	        "ORBIT", "OUTGO", "OVARY", "OVATE",
	        "OVINE", "OVOID", "OWING", "OZONE", "PADDY", "PAGAN", "PALER", "PALSY",
	        "PANSY", "PARKA", "PARSE", "PASTE", "PASTY", "PATCH", "PATSY",
	        "PAYEE", "PAYER", "PECAN", "PENAL", "PENCE", "PENNY", "PERIL",
            "PESTO", "PETAL", "PETTY", "PIGGY", "PITCH", "PIVOT",
	        "PIZZA", "PLACE", "PLAID", "PLAIN", "PLANE",
	        "PLEAD", "PLIED", "PLIER", "PLUME", "PLUMP", "PLUSH", "POESY", "POLAR", "POOCH",
	        "POPPY", "POSER", "POSIT", "POSSE", "POUCH", "POUTY", "PRANK", "PRAWN", "PREEN",
		    "PRIED", "PRISM", "PRIVY", "PROOF", 
		    "PRUDE", "PUBIC", "PUDGY", "PUFFY", "PULSE", "PUNCH",
		    "PUPPY", "PUREE", "PURER", "PURSE", "PUSHY", "PUTTY", "PYGMY", "QUACK", "QUAIL",
		    "QUAKE", "QUARK", "QUASH", "QUASI", "QUEER", "QUELL", "QUILL", "QUILT", 
		    "QUOTH", "RABBI", "RABID", "RACER", "RADAR", "RADII", "RAJAH", "RALLY", "RALPH",
		    "RANDY", "RARER", "RASPY", "RATTY", "RAVEN", "RAZOR", "REARM",
            "REBAR", "RECUT", "REEDY", "REFIT", "REHAB", "REIGN", "RELAY", "REMIT", "RENAL", 
            "REPLY", "RESET", "REUSE", "RIFLE", "RIGID", "RIGOR", "RINSE", "RIPEN", "RISER",
		    "RISKY", "RIVER", "ROAST", "ROGER", "ROOST", "ROTOR", "ROUGH",
		    "ROWDY", "RUGBY", "RULER", "RUMOR", "RURAL", "SADLY", "SAFER",
		    "SALON", "SALVE", "SALVO", "SANER", "SAPPY", "SATIN", "SATYR", "SAUCE",
		    "SAVOY", "SAVVY", "SCALP", "SCALY", "SCAMP", "SCARY", "SCENE",
		    "SCION", "SCOOP", "SCREE", "SCREW", "SCUBA", "SEGUE", 
            "SEIZE", "SEMEN", "SEPIA", "SERIF", "SETUP", "SEWER", "SHACK", "SHADY", 
            "SHALE", "SHALT", "SHARK", "SHEAR", "SHEEN", "SHEEP", "SHEER", 
            "SHEIK", "SHIED", "SHINY", "SHIRT", "SHOAL", "SHOCK", "SHONE", 
            "SHOOK", "SHOOT", "SHORT", "SHREW", "SHUCK", "SHUSH", 
            "SIEVE", "SIGMA", "SILKY", "SINEW", "SINGE", "SIREN", "SIXTY", 
		    "SKULK", "SKULL", "SLACK", "SLAIN", "SLANT", "SLASH", "SLAVE", "SLEET", 
            "SLEPT", "SLICK", "SLIDE", "SLIME", "SLIMY", "SLING", "SLINK", "SLOOP", "SLUNK", "SLURP", 
            "SLUSH", "SLYLY", "SMACK", "SMELL", "SMOKY", "SMOTE", "SNEER", "SNIDE", 
            "SNIFF", "SNIPE", "SNORE", "SNOWY", "SNUCK", "SNUFF", "SOAPY", "SOBER", "SONAR", 
            "SOOTH", "SOOTY", "SOUTH", "SPANK", "SPARE", "SPASM", "SPAWN",  
            "SPEED", "SPERM", "SPIED", "SPIKY", "SPILT", "SPINY", "SPLIT", 
            "SPOIL", "SPOOF", "SPOOK", "SPOOL", "SPORE", "SPORT", "SPREE", 
            "SPUNK", "SPURN", "SQUIB", "STACK", "STALK", "STALL", "STANK",
            "STAVE", "STEAK", "STEAL", "STEER", "STILT",  
            "STOKE", "STOOD", "STOOP", "STORK", "STRIP", "STRUT", "STUCK", 
            "STUFF", "STUMP", "STUNK", "STUNT",
	        "SUING", "SUITE", "SULLY", "SUMAC", "SURGE", "SWAMI", "SWAMP", "SWARM",
	        "SWASH", "SWEAR", "SWEPT", "SWIFT", "SWING", "SWOOP"
            "SWORD", "SWORE", "SWORN", "SYNOD", "TABBY", "TAFFY", "TAINT",
	        "TAKER", "TAMER", "TANGO", "TAROT", "TATTY", "TEARY", "TEDDY",
	        "TEETH", "TENET", "TENOR", "TENSE", "TEPEE", "TERRA", "TESTY", "THEFT",
	        "THETA", "THICK", "THONG", "THROB", "THRUM", "TIGHT", "TIMID",
	        "TODDY", "TOKEN", "TONAL", "TONER", "TONGA", 
	        "TORUS", "TOWER", "TRAMP", "TREAD",
	        "TRIAL", "TRIBE", "TRICK", "TRIED", "TRIPE", "TROUT", "TRUCE", "TRUCK", "TRUER",
	        "TRUMP", "TRUNK", "TUBAL", "TUBER", "TULIP", "TULLE", "TUMOR", "TURBO",
	        "TWEET", "TWIXT", "TYING", "UMBRA", "UNCUT", "UNDID",
	        "UNION", "UNITY", "UNSET", "UNWED", "URINE", "UTILE", "VALOR", 
	        "VALVE", "VAPOR", "VAUNT", "VEGAN", "VENUE", "VERSE", "VERSO",
	        "VICAR", "VIGIL", "VILLA", "VIPER", "VIRUS", "VISIT", "VISTA",
	        "VIXEN", "VOCAL", "VOGUE", "VOMIT", "VOWEL", "WAGER", 
	        "WAIST", "WAIVE", "WARTY", "WATER", "WAVER", "WAXEN", "WEAVE", "WEEDY", "WEIGH",
	        "WELCH", "WELSH", "WHARF", "WHEAT", "WHITE", "WHOLE", "WHOSE", 
	        "WIDER", "WIDOW", "WIDTH", "WIELD", "WIGHT", "WILLY", "WIMPY", "WINCH", "WISER", "WISPY",
	        "WITTY", "WOMEN", "WOODY", "WOOLY", "WOOZY", "WORTH", "WOUND", "WRACK", "WRECK", 
            "WREST", "WRING", "WRYLY", "YEAST", "ZONAL"
             ]

word = 'JEWEL'


if word in unused_list:
 print(f"{word} is in this list -  {word} is available! Guess {word}. Give {word} a try!")
else:
   print(f"{word} is not in this list! {word} has most likely already been used by Wordle.")



            




